[project]
name = "emotion-annotation-web"
version = "0.1.0"
description = "Emotion annotation web application"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn>=0.35.0",
]
